### ISSUE TITLE
Make character stats editable after creation

### ISSUE THREAD

**Issue by gvorbeck** [gvorbeck/codex-quest#179]
A user logged in and viewing one of their characters should be able to edit their charcater's stats even after character creation. Create a button that will put a portion of the character sheet page into an "edit mode" in order to make permanent changes to their character's stats.

- [x] ability scores
- [x] health point maximum

**Comment by gvorbeck** [comment]
This is done for the

**Comment by SixgunHobbit** [comment]
Thanks for putting this feature on the page. I've tried to use it on a couple of different devices and it's not working on PC (Firefox) or smartphone (Brave).

I click the edit icon and the ability scores change to be editable, however when I try to put in a number or use the up/down arrows, the page turns white and seems to lock up. I then must reload the page, but there is no update to the ability score.

Also, the HP box becomes editable when the icon is clicked, but neither the arrows work to alter the number, nor does entering a number seem to change it.

**Comment by gvorbeck** [comment]
I have confirmed this problem. Sorry for that, but thank you for reporting it. Will comment when I have a solution in place.

Good catch!

**Comment by gvorbeck** [comment]
This is happening because of a recent change to how the character creator works. If a person is creating a new character, makes choices and then goes back and changes those choices, I've to void out things in order to make sure they can't cheat the build by making a thief with a d100 hit die or something.

The ability score table uses that same code, so when you are changing your scores it is trying to void out your character's hit dice/class/race etc, which... breaks the page.

This will take me a bit of time, but I should have a solution by late tonight (EST timezone).

**Comment by gvorbeck** [comment]
@SixgunHobbit I have fixed both issues with site v2.0.7

Editing an existing character's stats should now work without crashing the page.

Editing an existing character's max hit dice should now allow you to type or click the arrows to change the value.
