### ISSUE TITLE
Unable to make a game

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#223]
When attempting to make a New Game, I fill in the name field but the submit button does nothing when pressed.

**Comment by gvorbeck** [comment]
lol how did that happen!? I'm on it.

**Comment by gvorbeck** [comment]
Well that was weird. Should be resolved now with site version 2.0.4 (version # is displayed in site footer)

Thanks so much for reporting that! Reopen if still unresolved.

**Comment by The-Sovereign-Psiocrat** [comment]
It's fixed now, awesome!

I realy appreciate the work you put into the site, can't wait to see how it evolves!
