### ISSUE TITLE
Game failed to open

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#226]
It successfully made a game, but after trying to access it, it failed to load and instead brought me to a white screen. To make sure it was not just me I had a friend try it too, and they had the same problem.

**Comment by gvorbeck** [comment]
Can you send me the URL of your game screen (the white screen) and is there anything in the browser console?

**Comment by The-Sovereign-Psiocrat** [comment]
Here you go!

https://codex.quest/u/TqJfMPZPyVe9SJtlIdMmnAk6dHu2/g/gIp0BUskGpy1WhtObXy6

**Comment by gvorbeck** [comment]
I just pushed a fix for this. Did this fix it for you?

**Comment by The-Sovereign-Psiocrat** [comment]
Yes, that did it!

Thanks again
