### ISSUE TITLE
Housekeeping: Non Intuitive Equipment

### ISSUE THREAD

**Issue by Gryphling** [gvorbeck/codex-quest#239]
Within the Equipment editing feature, it is unintuitive as to how to modify the amount of an equipment you have due to it not pulling the data of what is currently within the inventory and adding that for amounts. This means that you have to manually modify the individual equipment items starting with them appearing as to having zero, though it will replace the current amount of an equipment. It would be beneficial to either have a button to delete/modify amount for equipment, or to have it update the add/edit equipment menu with current equipment.

**Comment by gvorbeck** [comment]
You're absolutely right. I am adding that to the bug list and I will try to have it be part of my 2.3.0 release later this week.

Good catch.

**Comment by Gryphling** [comment]
Awesome, thanks for the update. I've tried to create a similar sort of service, though for a different RPG. I've got a huge understanding of how easy it is for stuff to slip through the cracks while working on the entirety of a project.

**Comment by gvorbeck** [comment]
I have updated this so that the current amount a user has in their inventory shows up in the "amount" field so that modifying it is a bit more intuitive. I'm seeing the weird behavior around gold refunds when modifying so it may need some more work in the near-term.
