### ISSUE TITLE
Idea: Turn Tracker

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#243]
This is just an idea based on your plan on a Combat Tracker, adding simple functionality for a Dungeon Turn Tracker (pg. 42 in BFRPG) would be useful. (with possible signifiers for torches or random encounters based on difficulty of implementation.)

its not an immediate issue, this is just a surprising hurdle when I run online sessions as there's really no good digital tool for tracking turns and thought I might as well bring it up.

**Comment by gvorbeck** [comment]
Let's collaborate a bit on this idea. Here's what I had envisioned the GM page to look like when that feature was finally implemented:

![imgonline-com-ua-dexifSMi3UQFyoLjo](https://github.com/gvorbeck/codex-quest/assets/1986380/5e12ad19-45bd-4e93-9112-7cf406d908d1)

* It would be a little pop-up in the lower-right of the GM page. Listed would be the PCs in initiative order (probably a text input for changing that initiative when needed).
* It would be collapsible to enable full view of the Game Binder (the right half of the page with notes/spells/etc)
* I could add toggle buttons for torches (colored would indicate the PC was using a torch) and maybe an eye icon if the player can see in the dark.
* GM would also be able to add or remove players and monsters as they needed.

How does this align with your thoughts?

**Comment by The-Sovereign-Psiocrat** [comment]
Wow it looks good I think this system for a Combat Tracker will work great, I like the collapsible aspect allowing for users to still access Monster Statblocks and the note section. My only note is to add AC to those in the combat tracker. Since monsters don't have static HP do you plan on having it roll for HP upon being added to combat or did you have something else in mind?

Also when I said torches I more mean't in regards to the 10 minute dungeon turns and how long they last (Ex. Torches are 1d4+4 Turns) and how in dungeons you have a random encounter roll every 3rd Dungeon Turn. I understand if thats not within the scope of the project tho.

**Comment by gvorbeck** [comment]
re AC: yes, good point. Will add.

re HP: exactly what I had in mind. Adding a monster will roll things like how many are appearing (I may have to implement something that asks if it's a lair... ugh) and HP.

re Turns: The turn stuff is tricky. I'm trying to strike a delicate balance of making C.Q a _helpful_ tool while not turning it into something that becomes overly complex (I believe DNDBeyond's tools are overly complex).

Some of this will be game-time decisions, but let's keep this issue open to come back to the discussion when I break ground on it. My timeline for this is late March, early April.

**Comment by The-Sovereign-Psiocrat** [comment]
That all sounds awesome, and that's very fair. I can easily see how a tool like this could become overly complex. So far, you have kept a good balance between intuitiveness and usefulness. I am now hyped to see the system in practice, from your sketches it looks very promising.

**Comment by gvorbeck** [comment]
I just launched a v1.0 of the Turn Tracker publicly (I'll wait a few days to announce it):
<img width="1200" alt="Screenshot 2024-02-27 at 2 16 31 PM" src="https://github.com/gvorbeck/codex-quest/assets/1986380/b331d9d3-9713-45a0-b2d7-3bde875828df">

It's similar in a lot of ways to what we previously discussed, but with some changes:
- Open it via the hourglass button on main GM screen
- Input field for initiative
- Batch roll initiative for monsters
- Ability to rename monster combatants (so you don't have 5 Giant Ants with the same name in the list)
- Directly add monsters to the Turn Tracker from the Monsters Tab on the main screen.
- Tagging system: This is a catch-all for a lot of different functionality (ex: conditions, torches, darkvision, etc). Basically, the GM can tag every combatant with whatever-they-want. It doesn't tick-down for each turn, so you'll need to keep track of those torches yourself, but I think this is a pretty dynamic solution that will accommodate lots of needs.

**Comment by The-Sovereign-Psiocrat** [comment]
Awesome! It looks great on my end. I love the tagging system and how flexible it is; it feels like it could be useful in a ton of situations in my game. My only major comment is that it feels like I will be constantly pressing the remove button by accident. I can see a confirmation after pressing the button as useful (or something similar).

**Comment by gvorbeck** [comment]
I'm so happy to hear that! It was a fun challenge to make, and of course I'll keep improving it over time. I just started playing in a PBP game and so I really wanted to get it done so that my GM could use it as well. 

Your confirm request is reasonable and easy so I just added it. When clicking the remove button, it'll now ask you to confirm the removal. Cheers!
