### ISSUE TITLE
Bug: Turn Tracker

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#262]
I was testing some stuff with the new Turn Tracker, in a game I made pre-update it works but I just made a new game today and when I press the button to add anything to the turn tracker it gives the notification for it being added, but is not added.

**Comment by gvorbeck** [comment]
Ugh, you're right. Thanks for noticing that and letting me know. 

As a bandaid, I've updated the site with a fix that allows all games to add PCs/Monsters to the Turn Tracker. However, it gets erased if you refresh the page. I'm trying to hunt down the original cause of all this, but at least I have a temporary fix in place.

**Comment by gvorbeck** [comment]
Okay! I think I've gotten the logic all worked out and fixed it. I can: 
* create a new game
* add a player to the game
* add that player to the turn tracker
* confirm they are present in the turn tracker
* refresh the page and see the same turn tracker data is present.

thanks for identifying a bug on a new feature so quickly!

**Comment by The-Sovereign-Psiocrat** [comment]
I'm glad I can help!
