### ISSUE TITLE
Thoughts on the Turn Tracker

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#268]
I have been using the new Tracker recently and have a few thoughts, also I saw you added all the core monsters, they look great!

- It's labeled as a "Turn Tracker," although in BFRPG, combat is measured in rounds rather than turns (pg. 42 BFRPG Core Rules).

- The confirmation for removing a player from the Turn Tracker has already proven useful for me. Perhaps you could add a similar feature for removing characters from the game, preventing GMs from accidentally removing PCs.

- The button for adding a character to the turn tracker uses the same icon as the one for removing a player, except with a plus sign. This feels awkward to me since they perform two very different functions. I have made a quick example icon, which I have attached.

![Hourglass +](https://github.com/gvorbeck/codex-quest/assets/132250843/808f3eee-a145-4c6e-9eff-96c8ed2b1eaf)

**Comment by gvorbeck** [comment]
These seem reasonable! Will work on these.

**Comment by gvorbeck** [comment]
I updated the name to Round Tracker and created new icons based on your thumbnail.
