### ISSUE TITLE
Allow reseting password

### ISSUE THREAD

**Issue by kmerfeld** [gvorbeck/codex-quest#283]
Currently I don't think there is a way to reset a password. I think firebase has flows to make this somewhat straightforward

**Comment by gvorbeck** [comment]
You're right. I need to look into how to add that functionality (I think I found some documentation for that here: https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email)

I'll try to get that added in the coming days. In the meantime, I can send password reset emails manually. Do you need me to send one to a particular email address now?

**Comment by kmerfeld** [comment]
I just used a made a myemail+codex@gmail.com account, so I'm fine for now.
Its not urgent for me, but a big usability stumbling block

**Comment by gvorbeck** [comment]
You're right. Thanks for bringing it to my attention, I appreciate it.

**Comment by gvorbeck** [comment]
I added a "Forgot password?" link on the Sign In form over the weekend. Tested it out on one of my dummy accounts and seems to work pretty well. Thanks for bringing this to my attention!
