### ISSUE TITLE
Bug: Custom Bows & Character Removal

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#289]
Hello just had a session Saturday and had a few bugs.

1. When using a custom made bow, the button to attack does not work.

2. For some reason in my older game I cannot remove players, (but for my newer ones you can)

Also as a note good work on the new cantrip options, I especially like putting some of the non-immediate options being put under settings, I imagine due to the amount of optional rules for BFRPG it will be useful.

**Comment by gvorbeck** [comment]
1. That is odd, but I will will investigate and fix this.
2. WEIRD! I wonder what the difference between the times the games were made means. 

Glad you like the changes. I'll get on these and another bug that was brought to my attention this morning. Should be wrapped up and fixed before your next session.

**Comment by The-Sovereign-Psiocrat** [comment]
Sounds good, thanks Gvorbeck

Also just discovered an additional bug, went to reroll the stats of a already made character and when I push the button to roll 3d6 or edit the stat number my screen goes white, My url does not change.

**Comment by gvorbeck** [comment]
That is the exact bug I was notified of this morning. That will also be eradicated.

**Comment by gvorbeck** [comment]
codex.quest v2.7.5 fixes the page crash on updating ability scores (the last issue you mentioned).

For a full description of the problem and why it was occurring, you can find that [HERE](https://github.com/gvorbeck/codex-quest/issues/288#issuecomment-2023141055)

I will update this issue when the rest of your documented bugs are addressed.

**Comment by gvorbeck** [comment]
codex.quest v2.7.6 fixes being unable to remove players from a game.

**Comment by gvorbeck** [comment]
The custom bow bug is tricky because i did some dumb things. I'm hoping to have a fix late tonight or some time tomorrow.

**Comment by gvorbeck** [comment]
codex.quest 2.7.9 fixes custom bows' attack modal. This required some refactoring as well as new development to fix a lapse in code. NOTE: previously created custom bows will still be broken, but newly created custom bows will work.
