### ISSUE TITLE
Blank screen upon loading into dashboard (Brave Browser)

### ISSUE THREAD

**Issue by Gryphling** [gvorbeck/codex-quest#338]
I was trying to open Codex.Quest, however when loading the dashboard I would load in the basic template for a second and just show up as blank. I tried to load into the character sheet directly, and that worked.

**Comment by Gryphling** [comment]
Update, this seems to be an issue with Brave Browser

**Comment by gvorbeck** [comment]
I have some time to look into this. I am checking on this tonight.

**Comment by gvorbeck** [comment]
I have installed Brave Browser on my Macbook and the site loads as expected. 
Tested:
* Logged out homepage
* Logged in homepage
* Character Sheet page
* Game Sheet page

This may be related to an out of date browser or perhaps an extension you have installed on your browser. I installed Brave Browser 1.66.118 with no extensions, freshly installed.

If this continues after disabling extensions and updating the browser, please reopen this issue with a copy of what is appearing in the browser's console (cmd + option + i)
