### ISSUE TITLE
A few bugs.

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#339]
I had my BFRPG session tonight and have a few bugs

1. We could not figure out how to change max HP if there was a way to it

2. From one of my players "Custom ammo can't be selected to be used by bows I can't change the quantity of custom ammo without making a new instance of the ammo type"

As always I appreciate the work you do, and I am excited to see what is added

**Comment by gvorbeck** [comment]
1) I see. I am able to add additional HP beyond the max, but the max remains the same. This is a good bug. I will fix this by making the edit button on HP only affect the max value, not the current value. TY
![Screenshot 2024-06-01 at 8 11 35 PM](https://github.com/gvorbeck/codex-quest/assets/1986380/e21ee5e1-afcc-4bed-aa02-7bab76cd2498)

2) UGH. This is a big bug. And one that will require some thinking and some work. I'll have to find a graceful way to be able to link custom ammo to a weapon. I hadn't thought about that before. Let me work on this a bit.

**Comment by gvorbeck** [comment]
Issue 1 re: Max HP is fixed. Clicking the edit button on the Hit Points section now only edits the Max value. Editing the current value is only done outside of the edit mode for that section.

**Comment by gvorbeck** [comment]
Alright,
I have a solution in place for issue 2:
- When a user selects a missile weapon (ex: a Shortbow), that weapon will list any ammunition that is related to that weapon (ex: Shortbow Arrow) AND any/all custom ammunition they have created for this character.
- Custom ammunition items now have an InputNumber field in the Amount field that allows them to alter the amount of that custom ammunition type. Default ammunition will not have this field and those amounts will be managed from the settings drawer as usual.
