### ISSUE TITLE
Player submitted bugs

### ISSUE THREAD

**Issue by The-Sovereign-Psiocrat** [gvorbeck/codex-quest#358]
I asked my players to submit bugs and just got a few.

-When editing/adding spells: all spells vanish if you search a single spell 
-After character is complete, editing stats removes equipment

**Comment by gvorbeck** [comment]
Wow, you and your players find the best bugs. I'm really thankful for you your group! 

I fixed the stats/equipment bug.

I do need some more help on the first issue as I can't reproduce it and I'm wondering if I'm misunderstanding

https://github.com/gvorbeck/codex-quest/assets/1986380/6293228e-2dbe-4583-a716-ef6955435865

**Comment by The-Sovereign-Psiocrat** [comment]
Of course, here you go.

https://www.youtube.com/watch?v=ct9RlH6SWDM

**Comment by gvorbeck** [comment]
Very helpful. Let me wrangle that one for your players.

**Comment by gvorbeck** [comment]
BOOM! Fixed both.
