### ISSUE TITLE
dark mode?

### ISSUE THREAD

**Issue by HomingChikn** [gvorbeck/codex-quest#372]
tired of being flash banged upon tab changes

**Comment by gvorbeck** [comment]
Yeah I can work on that. I just became a father last week so it'll be a bit. In the mean time, there are good browser extensions for that.

**Comment by The-Sovereign-Psiocrat** [comment]
Congrats!

**Comment by gvorbeck** [comment]
I have started work on this. Will update this issue when I have something to show.

**Comment by gvorbeck** [comment]
Okay, v2.13.0 implements a rudimentary dark mode button in the header. There are several things that can be improved upon which I will get to in time, but this should put an end to the flash bangs ;)
