### ISSUE TITLE
Magic-User class has no selectable equipment or items and cannot be created

### ISSUE THREAD

**Issue by DC23** [gvorbeck/codex-quest#51]
I've confirmed with the current prod instance. Both human and elf Magic-Users have no selectable items, which means those characters cannot be created at all. After poking around in the code to see how I could add Druid, I've an idea of what might be going on, but can't confirm until I get my own database setup working.

**Comment by gvorbeck** [comment]
Wow, good catch. I really need to prioritize writing tests for this site as it's becoming more complex. This should be fixed now.

**Comment by gvorbeck** [comment]
btw, i have soft-launched Druid class. Gonna be sanity checking it for a day or so before making any announcements. I have already identified a bug with the Saving Throws table that I am refactoring, but just working out the kinks.
