### ISSUE TITLE
Manually entering ability scores does not work

### ISSUE THREAD

**Issue by DC23** [gvorbeck/codex-quest#70]
When entering an ability score manually, each keypress randomises the ability score. Clicking the up/down spinner buttons has the same effect. The only way to get the desired ability scores is to keep spamming the randomise button until the required result is rolled.

Detected in v1.10.0.0 by multiple testers in multiple browsers, as I asked the players in a game to all create their characters in CQ using rolls they had made elsewhere.

**Comment by gvorbeck** [comment]
Confirmed. Will be fixed within 24 hrs of this comment.

**Comment by gvorbeck** [comment]
Fixed w/ `v1.10.0.1` now live. Users can click the Roll button to receive a random value, they can manually type in their values, and they can click the up/down buttons that appear when hovering over the input.
