### ISSUE TITLE
Migrate from CRA to Vite

### ISSUE THREAD

**Issue by gvorbeck** [gvorbeck/codex-quest#72]
CRA is dead, and apparently has been for some time. Current community seems to favor Vite so C.Q should migrate to Vite in order to take advantages of updated packages like TypeScript 5 as CRA is no longer being maintained.

Guide to migrate from CRA: https://www.asserts.ai/blog/migrataion-react-cra-vitejs/

**Comment by GIT-Gizmo** [comment]
Is this issue still open?. I can help with it

**Comment by gvorbeck** [comment]
It is still open. Feel free to give it a whirl. I have never used Vite before nor migrated away from CRA so it's new territory for me. Have you done it before?

Feel free to create a fork and open a PR with your work when complete. Thanks!

**Comment by GIT-Gizmo** [comment]
Sure, I've done it before. Happy to help

**Comment by GIT-Gizmo** [comment]
I've migrated to vite but the web page shows a white blank page and the console refers to an error in the firebase.js file which I believe might be an incompatibility issue. I'll try my best to so if I can fix it

**Comment by gvorbeck** [comment]
It might also have to do with not having access to my environment secrets

**Comment by GIT-Gizmo** [comment]
Oh, that's right. Is there some special tweak I need to do? You can let me know  if you don't mind

**Comment by gvorbeck** [comment]
I currently have no setup for viewing the site without the environment
secrets unfortunately.

**Comment by GIT-Gizmo** [comment]
Ah, I see

**Comment by gvorbeck** [comment]
it is something I plan to implement in the future though.

**Comment by GIT-Gizmo** [comment]
That's great, I'll be checking in on the project once in a while, happy to help whenever

**Comment by gvorbeck** [comment]
Here's a problem:
I've been attempting to do the Vite migration myself and am nearly done, except for images. In CRA images didn't have two different URLs depending on environment like Vite does: ("For example, imgUrl will be /img.png during development, and become /assets/img.2d8efhg.png in the production build. source: https://vitejs.dev/guide/assets.html) So now all the calls to the database to get a character's avatar return the production url:

<img width="1671" alt="Screenshot 2023-08-31 at 4 55 56 PM" src="https://github.com/gvorbeck/codex-quest/assets/1986380/2853db68-99dc-4e95-8c4b-f5ded46ab251">
