### ISSUE TITLE
Manual entry of values triggers randomisation

### ISSUE THREAD

**Issue by DC23** [gvorbeck/codex-quest#78]
This is an extension of #70. The same behaviour has been identified on the roll for hit points screen. However, the results are not completely random. For a human fighter with CON 14, typing 9 consistently produces the value 11. Backspacing once changes the value to 3. Backspacing a second time to empty the input and typing 9 repeats the cycle. Other numbers have similar patterns. It's very odd from a user perspective.

Tested in v1.11.1.2

**Comment by gvorbeck** [comment]
This is now fixed in`v1.11.1.3`

- Clicking the roll button will give a random number PLUS the character's Constitution bonus/penalty. 
- Typing allows the user to set a specific value. This value can be set to anything from 1 to... very large numbers.
