### ISSUE TITLE
Cannot enter gold amounts less than 30

### ISSUE THREAD

**Issue by DC23** [gvorbeck/codex-quest#79]
Tested in v1.11.1.2

In the character creation workflow, manually entering an amount for gold only works if the amount entered is greater than 30. If less than 30 gold is entered, the value is changed to 30 gold. This creates problems, for example when entering a character that was already created elsewhere.

**Comment by gvorbeck** [comment]
Ah, this is because when rolling a new character, a player is to use 3d6x10 which means 30 is the lowest possible amount. I understand the point however of recreating a character from elsewhere and can remove this limitation.

**Comment by gvorbeck** [comment]
This is fixed in `v1.11.1.4`

Users can now type in a value lower than 30
